version: "3.8"
services:
  client:
    container_name: client
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
